/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BiologyRouteImport } from './routes/biology'
import { Route as CeilingRouteImport } from './routes/ceiling'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as StackRouteImport } from './routes/stack'
import { Route as ToothRouteRouteImport } from './routes/tooth/route'
import { Route as ToothIndexRouteImport } from './routes/tooth/index'
import { Route as ToothLabRouteImport } from './routes/tooth/lab'
import { Route as ToothOrganRouteImport } from './routes/tooth/organ'
import { Route as ToothPipelineRouteImport } from './routes/tooth/pipeline'
import { Route as ToothStackRouteImport } from './routes/tooth/stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BiologyRoute = BiologyRouteImport.update({
  id: '/biology',
  path: '/biology',
  getParentRoute: () => rootRouteImport,
} as any)
const CeilingRoute = CeilingRouteImport.update({
  id: '/ceiling',
  path: '/ceiling',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ToothRouteRoute = ToothRouteRouteImport.update({
  id: '/tooth',
  path: '/tooth',
  getParentRoute: () => rootRouteImport,
} as any)
const ToothIndexRoute = ToothIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToothRouteRoute,
} as any)
const ToothLabRoute = ToothLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => ToothRouteRoute,
} as any)
const ToothOrganRoute = ToothOrganRouteImport.update({
  id: '/organ',
  path: '/organ',
  getParentRoute: () => ToothRouteRoute,
} as any)
const ToothPipelineRoute = ToothPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ToothRouteRoute,
} as any)
const ToothStackRoute = ToothStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => ToothRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tooth': typeof ToothRouteRouteWithChildren
  '/biology': typeof BiologyRoute
  '/ceiling': typeof CeilingRoute
  '/desk': typeof DeskRoute
  '/lab': typeof LabRoute
  '/pipeline': typeof PipelineRoute
  '/stack': typeof StackRoute
  '/tooth/lab': typeof ToothLabRoute
  '/tooth/organ': typeof ToothOrganRoute
  '/tooth/pipeline': typeof ToothPipelineRoute
  '/tooth/stack': typeof ToothStackRoute
  '/tooth/': typeof ToothIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biology': typeof BiologyRoute
  '/ceiling': typeof CeilingRoute
  '/desk': typeof DeskRoute
  '/lab': typeof LabRoute
  '/pipeline': typeof PipelineRoute
  '/stack': typeof StackRoute
  '/tooth/lab': typeof ToothLabRoute
  '/tooth/organ': typeof ToothOrganRoute
  '/tooth/pipeline': typeof ToothPipelineRoute
  '/tooth/stack': typeof ToothStackRoute
  '/tooth': typeof ToothIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tooth': typeof ToothRouteRouteWithChildren
  '/biology': typeof BiologyRoute
  '/ceiling': typeof CeilingRoute
  '/desk': typeof DeskRoute
  '/lab': typeof LabRoute
  '/pipeline': typeof PipelineRoute
  '/stack': typeof StackRoute
  '/tooth/lab': typeof ToothLabRoute
  '/tooth/organ': typeof ToothOrganRoute
  '/tooth/pipeline': typeof ToothPipelineRoute
  '/tooth/stack': typeof ToothStackRoute
  '/tooth/': typeof ToothIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tooth'
    | '/biology'
    | '/ceiling'
    | '/desk'
    | '/lab'
    | '/pipeline'
    | '/stack'
    | '/tooth/lab'
    | '/tooth/organ'
    | '/tooth/pipeline'
    | '/tooth/stack'
    | '/tooth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biology'
    | '/ceiling'
    | '/desk'
    | '/lab'
    | '/pipeline'
    | '/stack'
    | '/tooth/lab'
    | '/tooth/organ'
    | '/tooth/pipeline'
    | '/tooth/stack'
    | '/tooth'
  id:
    | '__root__'
    | '/'
    | '/tooth'
    | '/biology'
    | '/ceiling'
    | '/desk'
    | '/lab'
    | '/pipeline'
    | '/stack'
    | '/tooth/lab'
    | '/tooth/organ'
    | '/tooth/pipeline'
    | '/tooth/stack'
    | '/tooth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToothRouteRoute: typeof ToothRouteRouteWithChildren
  BiologyRoute: typeof BiologyRoute
  CeilingRoute: typeof CeilingRoute
  DeskRoute: typeof DeskRoute
  LabRoute: typeof LabRoute
  PipelineRoute: typeof PipelineRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biology': {
      id: '/biology'
      path: '/biology'
      fullPath: '/biology'
      preLoaderRoute: typeof BiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceiling': {
      id: '/ceiling'
      path: '/ceiling'
      fullPath: '/ceiling'
      preLoaderRoute: typeof CeilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooth': {
      id: '/tooth'
      path: '/tooth'
      fullPath: '/tooth'
      preLoaderRoute: typeof ToothRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tooth/': {
      id: '/tooth/'
      path: '/'
      fullPath: '/tooth/'
      preLoaderRoute: typeof ToothIndexRouteImport
      parentRoute: typeof ToothRouteRoute
    }
    '/tooth/lab': {
      id: '/tooth/lab'
      path: '/lab'
      fullPath: '/tooth/lab'
      preLoaderRoute: typeof ToothLabRouteImport
      parentRoute: typeof ToothRouteRoute
    }
    '/tooth/organ': {
      id: '/tooth/organ'
      path: '/organ'
      fullPath: '/tooth/organ'
      preLoaderRoute: typeof ToothOrganRouteImport
      parentRoute: typeof ToothRouteRoute
    }
    '/tooth/pipeline': {
      id: '/tooth/pipeline'
      path: '/pipeline'
      fullPath: '/tooth/pipeline'
      preLoaderRoute: typeof ToothPipelineRouteImport
      parentRoute: typeof ToothRouteRoute
    }
    '/tooth/stack': {
      id: '/tooth/stack'
      path: '/stack'
      fullPath: '/tooth/stack'
      preLoaderRoute: typeof ToothStackRouteImport
      parentRoute: typeof ToothRouteRoute
    }
  }
}

interface ToothRouteRouteChildren {
  ToothLabRoute: typeof ToothLabRoute
  ToothOrganRoute: typeof ToothOrganRoute
  ToothPipelineRoute: typeof ToothPipelineRoute
  ToothStackRoute: typeof ToothStackRoute
  ToothIndexRoute: typeof ToothIndexRoute
}

const ToothRouteRouteChildren: ToothRouteRouteChildren = {
  ToothLabRoute: ToothLabRoute,
  ToothOrganRoute: ToothOrganRoute,
  ToothPipelineRoute: ToothPipelineRoute,
  ToothStackRoute: ToothStackRoute,
  ToothIndexRoute: ToothIndexRoute,
}

const ToothRouteRouteWithChildren = ToothRouteRoute._addFileChildren(
  ToothRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToothRouteRoute: ToothRouteRouteWithChildren,
  BiologyRoute: BiologyRoute,
  CeilingRoute: CeilingRoute,
  DeskRoute: DeskRoute,
  LabRoute: LabRoute,
  PipelineRoute: PipelineRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
